#Comments per week

This is temporary, but we need to put the fullUserComment data into a sql table:

In [ ]:
import os
os.chdir('/Users/alexsutherland/Dropbox/Insight/WeightLossReddit/')

fullCommentData = pd.read_csv('Data/fullCommentData.csv')

In [29]:
fullCommentData.head()

,Unnamed: 0,score,controversiality,body,subreddit,username,userid
0,0,1,0,You won't regret it for sure! : P it's uk size...,loseit,sweetpeach206,1
1,1,1,0,I always tell my self it's better to point eve...,PointsPlus,sweetpeach206,1
2,2,1,0,Thanks a lot and good luck with your journey!,loseit,sweetpeach206,1
3,3,1,0,"You don't have to lift weights to lose weight,...",progresspics,sweetpeach206,1
4,4,2,0,Awsome! You have something to be really proud ...,progresspics,sweetpeach206,1

There was a nan field that we need to fill in or get rid of in order to export to SQL

In [25]:
fullCommentData.ix[fullCommentData.isnull().apply(lambda x: any(x), axis=1),:]

,Unnamed: 0,score,controversiality,body,subreddit,username,userid
7598,7598,1,0,The Schrader family: 2,NaN,NaN,NaN
7599,The White family: 0,breakingbad,MasterBlitzkrieg,22,NaN,NaN,NaN
13508,13507,2,0,Really easy with a ceramic rod like you get wi...,NaN,NaN,NaN
13509,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13510,Edit: Just occurred to me that you might have ...,knives,familyphotoshoot,53,NaN,NaN,NaN
13516,13513,16,0,I hope the info about the Mirror Knight boss s...,NaN,NaN,NaN
13517,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13518,It sounds like such an awesome callback to the...,darksouls,familyphotoshoot,53,NaN,NaN,NaN
13522,13517,2,0,Agreed. There's nothing fun about farming upgr...,NaN,NaN,NaN
13523,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13524,The 360 save editor has been a huge timesaver ...,darksouls,familyphotoshoot,53,NaN,NaN,NaN
13525,13518,1,0,http://m.youtube.com/#/watch?v=uagxzTrtsiI,NaN,NaN,NaN
13526,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13527,Definitely possible to forcefeed someone souls.,darksouls,familyphotoshoot,53,NaN,NaN,NaN
30430,30421,10,0,My nightstand -- first thing I reach for in th...,NaN,NaN,NaN
30431,http://i.imgur.com/su4eFd9.jpg,electronic_cigarette,romantivist,84,NaN,NaN,NaN
57826,57816,1,0,NaN,pics,littlestmuffin,159
64114,64104,1,0,You'd get people coming in early and you'd tel...,NaN,NaN,NaN
64115,NaN,NaN,NaN,NaN,NaN,NaN,NaN
64116,Five minutes later you'd get people demanding ...,AskReddit,francescakate,181,NaN,NaN,NaN
64125,64113,2,0,I broke my arm falling out of a car. It's not ...,NaN,NaN,NaN
64126,NaN,NaN,NaN,NaN,NaN,NaN,NaN
64127,It was parked. I tripped over the seatbelt.,AskReddit,francescakate,181,NaN,NaN,NaN
64134,64120,0,0,Not exactly a food but milkshakes/flavoured mi...,NaN,NaN,NaN
64135,NaN,NaN,NaN,NaN,NaN,NaN,NaN
64136,I also have a weird thing about fishcakes. Jus...,AskReddit,francescakate,181,NaN,NaN,NaN
74086,74070,2,0,Vegetarian here.,NaN,NaN,NaN
74087,NaN,NaN,NaN,NaN,NaN,NaN,NaN
74088,I make this quite regularly. I also make jack...,NaN,NaN,NaN,NaN,NaN,NaN
74089,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...
174503,NaN,AdviceAnimals,Resistiane,490,NaN,NaN,NaN
174567,174462,1,0,They don't have to think before they speak. Th...,NaN,NaN,NaN
174568,NaN,NaN,NaN,NaN,NaN,NaN,NaN
174569,Source: Former Republican that voted blindly f...,politics,Resistiane,490,NaN,NaN,NaN
174599,174492,1,0,&gt;with a million frilly things you can't touch.,NaN,NaN,NaN
174600,NaN,NaN,NaN,NaN,NaN,NaN,NaN
174601,Stop dating gramdma's and this will probably s...,AdviceAnimals,Resistiane,490,NaN,NaN,NaN
185365,185256,0,0,NaN,nostalgia,MMDP700,523
199695,199586,-17,0,I'd date both versions of you! Well done!,NaN,NaN,NaN
199696,NaN,NaN,NaN,NaN,NaN,NaN,NaN
199697,Edit: why the down votes?,progresspics,akkadian6012,567,NaN,NaN,NaN
208423,208312,10,0,Indian smell requires some serious work to be ...,NaN,NaN,NaN
208424,NaN,NaN,NaN,NaN,NaN,NaN,NaN
208425,Then mix it with around 20ml of local toilet c...,NaN,NaN,NaN,NaN,NaN,NaN
208426,NaN,NaN,NaN,NaN,NaN,NaN,NaN
208427,The most effective method I know for cleaning ...,india,lenindc,604,NaN,NaN,NaN
253321,253206,4,0,NaN,teenagers,Allpurposesandals,774
253332,253217,9,0,NaN,teenagers,Allpurposesandals,774
253459,253344,1,0,NaN,teenagers,Allpurposesandals,774
253536,253421,3,0,NaN,teenagers,Allpurposesandals,774
270453,270338,1,0,My mother's side of the family seems to think ...,NaN,NaN,NaN
270454,1. If you're visiting me we don't talk about p...,NaN,NaN,NaN,NaN,NaN,NaN
270455,2. If you decide to bring up politics while I'...,NaN,NaN,NaN,NaN,NaN,NaN
270456,NaN,NaN,NaN,NaN,NaN,NaN,NaN
270457,Some people just can't be reasoned with.,AskReddit,TinyB1,836,NaN,NaN,NaN
270525,270406,168,0,I have never wanted a stove this much in my e...,NaN,NaN,NaN
270526,NaN,NaN,NaN,NaN,NaN,NaN,NaN
270527,Edit: And my highest ever upvoted comment is a...,DIY,TinyB1,836,NaN,NaN,NaN
291758,291637,5,0,What kills me is all the motorists focus on th...,NaN,NaN,NaN
291759,NaN,bikecommuting,eccentricfather,922,NaN,NaN,NaN

Let's remove any row that has a NaN

In [27]:
fullCommentData_NaNRemoved = fullCommentData.dropna()

In [28]:
redditDataIO.exportDataToSQL(fullCommentData_NaNRemoved, tableName='fullCommentData')

Index([u'Unnamed: 0', u'score', u'controversiality', u'body', u'subreddit', u'username', u'userid'], dtype='object')
Exported Data to SQL Table (Name: fullCommentData)

Now the data is in the SQL table

In [1]:
import numpy as np
import pandas as pd

Let's load the data:

In [2]:
import sys
sys.path.append('/Users/alexsutherland/Dropbox/Insight/WeightLossReddit/')
import redditDataIO

In [14]:
rawCommentData = redditDataIO.loadData(tableName='fullCommentData')
rawCommentData['created_utc'].head()

0    1363650000
1    1369870000
2    1418240000
3    1363990000
4    1379890000
Name: created_utc, dtype: float64

To get the average comments per week for each user. We should get the first date they posted on.

In [87]:
firstCommentDate = rawCommentData.groupby(['username'])['created_utc'].min()
firstCommentDate

username
-BeatrixKiddo-         1417280000
-ClarkNova-            1426870000
0verstim               1397190000
109epz                 1379000000
110100                 1410970000
1122boogiewoogieave    1387850000
11235813213455away     1426890000
1440hours              1383520000
2013orBust             1433250000
2014flhx               1433350000
20stud                 1402200000
235to150realquick      1431450000
25pains                1402600000
2EZ711                 1376060000
2gainz                 1387350000
...
zebeev              1402520000
zeldaguy0           1429110000
zemog333            1426700000
zen_bee             1401320000
zenjaba             1382030000
zerokaleidoscope    1424750000
ziggy101501         1394810000
zildjian3           1385340000
zippo11             1389880000
zirconst            1424470000
zoeypantalones      1382290000
zukamiku            1384130000
zurie               1399150000
zutari              1430620000
zybk                1426170000
Name: created_utc, Length: 3343, dtype: float64

If we now subtract the current date by each user's first date of commenting, we can get the time range the user has posted in:

In [89]:
timeSinceFirstComment = 1434576566 - firstCommentDate
timeSinceFirstComment

username
-BeatrixKiddo-         17296566
-ClarkNova-             7706566
0verstim               37386566
109epz                 55576566
110100                 23606566
1122boogiewoogieave    46726566
11235813213455away      7686566
1440hours              51056566
2013orBust              1326566
2014flhx                1226566
20stud                 32376566
235to150realquick       3126566
25pains                31976566
2EZ711                 58516566
2gainz                 47226566
...
zebeev              32056566
zeldaguy0            5466566
zemog333             7876566
zen_bee             33256566
zenjaba             52546566
zerokaleidoscope     9826566
ziggy101501         39766566
zildjian3           49236566
zippo11             44696566
zirconst            10106566
zoeypantalones      52286566
zukamiku            50446566
zurie               35426566
zutari               3956566
zybk                 8406566
Name: created_utc, Length: 3343, dtype: float64

We also need the total number of posts by user:

In [91]:
totalCommentByUser = rawCommentData['username'].value_counts()
totalCommentsByUser

username
-BeatrixKiddo-         1
-ClarkNova-            1
0verstim               1
109epz                 1
110100                 1
1122boogiewoogieave    1
11235813213455away     1
1440hours              1
2013orBust             1
2014flhx               1
20stud                 1
235to150realquick      1
25pains                1
2EZ711                 1
2gainz                 1
...
zebeev              1
zeldaguy0           1
zemog333            1
zen_bee             1
zenjaba             2
zerokaleidoscope    1
ziggy101501         1
zildjian3           1
zippo11             1
zirconst            1
zoeypantalones      1
zukamiku            1
zurie               1
zutari              1
zybk                1
Name: index, Length: 3343, dtype: int64

##TODO:
Let's also see if we can easily get the number of comments before and after the transformation: